# .goreleaser.yaml
version: 2

project_name: swiftstack

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/swiftstack

archives:
  - format: tar.gz
    # use zip for windows
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

# Homebrew Tap Integration
brews:
  - name: swiftstack
    repository:
      owner: 004Ongoro
      name: homebrew-tap
    homepage: "https://github.com/004Ongoro/swiftstack"
    description: "High-speed project scaffolder using binary slices."

# Scoop Bucket Integration
scoops:
  - name: swiftstack
    repository:
      owner: 004Ongoro
      name: scoop-bucket
    homepage: "https://github.com/004Ongoro/swiftstack"
    description: "High-speed project scaffolder using binary slices."

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'